apiVersion: v1
kind: Service
metadata:
  name: spring-web-api
  namespace: postgresql-haproxy-pgbouncer
spec:
  selector:
    app: spring-web-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
