apiVersion: v1
kind: Service
metadata:
  name: spring-web-api
  namespace: postgresql-haproxy-pgbouncer
spec:
  clusterIP: 10.96.174.4
  ports:
  - name: spring-web-api
    nodePort: 32634
    port: 8080
  selector:
    app: spring-web-api
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 198.51.100.0