apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy-exporter
  namespace: postgresql-haproxy-pgbouncer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haproxy-exporter
  template:
    metadata:
      labels:
        app: haproxy-exporter
    spec:
      containers:
        - name: haproxy-exporter
          image: quay.io/prometheus/haproxy-exporter:v0.15.0
          command:
            - "--haproxy.scrape-uri=http://admin:admin@haproxy:1936/stats;csv;csv;norefresh"
          ports:
            - containerPort: 9101
---
apiVersion: v1
kind: Service
metadata:
  name: haproxy-exporter
  namespace: postgresql-haproxy-pgbouncer
spec:
  selector:
    app: haproxy-exporter
  ports:
    - protocol: TCP
      port: 9101
      targetPort: 9101
