apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgbouncer-exporter
  namespace: postgresql-haproxy-pgbouncer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgbouncer-exporter
  template:
    metadata:
      labels:
        app: pgbouncer-exporter
    spec:
      containers:
        - name: pgbouncer-exporter
          image: quay.io/prometheuscommunity/pgbouncer-exporter
          env:
            - name: PGBOUNCER_URI
              value: "postgres://admin:admin123@pgbouncer:6432/pgbouncer?sslmode=disable"
            - name: PGBOUNCER_EXPORTER_CONNECTION_STRING
              value: "postgres://admin:admin123@pgbouncer:6432/pgbouncer?sslmode=disable"
          ports:
            - containerPort: 9127
---
apiVersion: v1
kind: Service
metadata:
  name: pgbouncer-exporter
  namespace: postgresql-haproxy-pgbouncer
spec:
  selector:
    app: pgbouncer-exporter
  ports:
    - protocol: TCP
      port: 9127
      targetPort: 9127
