apiVersion: v1
kind: ConfigMap
metadata:
  name: jmeter-config
  namespace: postgresql-haproxy-pgbouncer
data:
  test-plan.jmx: |-
    <?xml version="1.0" encoding="UTF-8"?>
    <jmeterTestPlan version="1.2" properties="5.0" jmeter="5.6.2">
      <hashTree>
        <TestPlan guiclass="TestPlanGui" testclass="TestPlan" testname="Test Plan" enabled="true">
          <boolProp name="TestPlan.functional_mode">false</boolProp>
        </TestPlan>
        <hashTree>
          <ThreadGroup guiclass="ThreadGroupGui" testclass="ThreadGroup" testname="Thread Group" enabled="true">
            <stringProp name="ThreadGroup.num_threads">${__P(users,1)}</stringProp>
            <stringProp name="ThreadGroup.ramp_time">${__P(rampup,1)}</stringProp>
            <stringProp name="ThreadGroup.duration">${__P(duration,60)}</stringProp>
            <elementProp name="ThreadGroup.main_controller" elementType="LoopController">
              <stringProp name="LoopController.loops">1</stringProp>
            </elementProp>
          </ThreadGroup>
          <hashTree>
            <CSVDataSet guiclass="TestBeanGUI" testclass="CSVDataSet" testname="CSV Data Set Config" enabled="true">
              <stringProp name="delimiter">,</stringProp>
              <stringProp name="filename">/data/data.csv</stringProp>
              <stringProp name="ignoreFirstLine">true</stringProp>
              <stringProp name="variableNames">customer_id,delivery_status</stringProp>
            </CSVDataSet>
            <hashTree/>
            <HTTPSamplerProxy guiclass="HttpTestSampleGui" testclass="HTTPSamplerProxy" testname="HTTP GET Request" enabled="true">
              <stringProp name="HTTPSampler.domain">spring-web-api</stringProp>
              <stringProp name="HTTPSampler.port">8080</stringProp>
              <stringProp name="HTTPSampler.protocol">http</stringProp>
              <stringProp name="HTTPSampler.path">/api/deliveries</stringProp>
              <stringProp name="HTTPSampler.method">GET</stringProp>
              <stringProp name="HTTPSampler.query">deliveryStatus=${delivery_status}&amp;customerId=${customer_id}</stringProp>
            </HTTPSamplerProxy>
            <hashTree/>
          </hashTree>
        </hashTree>
      </hashTree>
    </jmeterTestPlan>

  data.csv: |-
    customer_id,delivery_status
    77,delivered
    88,pending
    99,in_transit

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmeter-test
  namespace: postgresql-haproxy-pgbouncer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jmeter-test
  template:
    metadata:
      labels:
        app: jmeter-test
    spec:
      containers:
      - name: jmeter
        image: justb4/jmeter:latest
        command: ["sh", "-c", "jmeter -Djava.awt.headless=true -n -t /data/test-plan.jmx -l /data/results.jtl -Jusers=2000 -Jrampup=2000 -Jduration=2900"]
        volumeMounts:
        - name: jmeter-config
          mountPath: /data
      volumes:
      - name: jmeter-config
        configMap:
          name: jmeter-config
