apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: postgresql-haproxy-pgbouncer
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'postgres'
        static_configs:
          - targets: ['postgres-exporter:9187']
        metrics_path: '/metrics'
        scheme: 'http'

      - job_name: 'pgbouncer'
        static_configs:
          - targets: ['pgbouncer-exporter:9127']
        metrics_path: '/metrics'
        scheme: 'http'

      - job_name: 'haproxy'
        static_configs:
          - targets: ['haproxy-exporter:9101']
        metrics_path: '/metrics'
        scheme: 'http'

      - job_name: 'node-exporter'
        static_configs:
          - targets: ['node-exporter:9100']

      - job_name: 'spring-web-api'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['spring-web-api:8080']
