apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: postgresql-haproxy-pgbouncer
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'postgres'
        static_configs:
          - targets: ['postgres-exporter:9187']
        metrics_path: '/metrics'
        scheme: 'http'

      - job_name: 'pgbouncer'
        static_configs:
          - targets: ['pgbouncer-exporter:9127']
        metrics_path: '/metrics'
        scheme: 'http'

      - job_name: 'haproxy'
        static_configs:
          - targets: ['haproxy-exporter:9101']
        metrics_path: '/metrics'
        scheme: 'http'

      - job_name: 'node-exporter'
        static_configs:
          - targets: ['node-exporter:9100']

      - job_name: 'spring-web-api'
        metrics_path: '/actuator/prometheus'
        kubernetes_sd_configs:
          - role: pod  # Pod'ları keşfet
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: keep
            regex: spring-web-api  # Sadece bu etikete sahip pod'ları al
          - source_labels: [__meta_kubernetes_pod_container_port_name]
            action: keep
            regex: http  # Sadece "http" port'u olan pod'ları al
          - source_labels: [__meta_kubernetes_pod_ip]
            target_label: __address__
            replacement: $1:8080  # Pod IP'sini ve portunu hedef olarak ayarla
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: instance  # Pod adını "instance" etiketi olarak ekle