apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-cluster-rolebinding
subjects:
- kind: ServiceAccount
  name: prometheus-serviceaccount
  namespace: postgresql-haproxy-pgbouncer
roleRef:
  kind: ClusterRole
  name: prometheus-cluster-role
  apiGroup: rbac.authorization.k8s.io
