apiVersion: v1
kind: Service
metadata:
  name: haproxy
  namespace: postgresql-haproxy-pgbouncer
spec:
  ports:
    - name: primary
      port: 5432
      targetPort: 5432
    - name: replica
      port: 5433
      targetPort: 5433
    - name: stats
      port: 1936
      targetPort: 1936
  selector:
    app: haproxy
  type: ClusterIP
