apiVersion: v1
kind: ConfigMap
metadata:
  name: pgbouncer-config
  namespace: postgresql-haproxy-pgbouncer
data:
  pgbouncer.ini: |
    [databases]
    mydb = host=postgres-master port=5432 dbname=mydb user=admin password=admin123  pool_size=100 reserve_pool_size=5
    replica1 = host=postgres-replica1 port=5432 dbname=mydb user=admin password=admin123 pool_size=100 reserve_pool_size=5
    replica2 = host=postgres-replica2 port=5432 dbname=mydb user=admin password=admin123 pool_size=100 reserve_pool_size=5

    [pgbouncer]
    listen_port = 6432
    listen_addr = 0.0.0.0
    auth_type = md5
    auth_file = /etc/pgbouncer/userlist.txt
    pool_mode = transaction
    max_client_conn = 100
    default_pool_size = 100
    server_idle_timeout = 60
    ignore_startup_parameters = application_name,extra_float_digits
    admin_users = admin
    stats_users = admin
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pgbouncer-userlist
  namespace: postgresql-haproxy-pgbouncer
data:
  userlist.txt: |
    "admin" "md5ed348175a97f96082cb9605d89caa099"
    "stats" "md525d58b34e8d2ccfbd372cb19f38e2c3c"
    "postgres" "md532e12f215ba27cb750c9e093ce4b5127"
    "admin" "admin123"
    "stats" "md525d58b34e8d2ccfbd372cb19f38e2c3c"
    "postgres" "admin123"
