apiVersion: v1
kind: ConfigMap
metadata:
  name: pgbouncer-config
  namespace: postgresql-haproxy-pgbouncer
data:
  pgbouncer.ini: |
    [databases]
    mydb = host=postgres-master port=5432 dbname=mydb user=admin password=admin123

    [pgbouncer]
    listen_port = 6432
    listen_addr = 0.0.0.0
    auth_type = md5
    auth_file = /etc/pgbouncer/userlist.txt
    pool_mode = transaction
    max_client_conn = 100
    default_pool_size = 20
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pgbouncer-userlist
  namespace: postgresql-haproxy-pgbouncer
data:
  userlist.txt: |
    "admin" "md5$(echo -n 'admin123admin' | md5sum | awk '{print $1}')"
