apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgbouncer
  namespace: postgresql-haproxy-pgbouncer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgbouncer
  template:
    metadata:
      labels:
        app: pgbouncer
    spec:
      containers:
        - name: pgbouncer
          image: edoburu/pgbouncer
          ports:
            - containerPort: 6432
          volumeMounts:
            - name: pgbouncer-config
              mountPath: /etc/pgbouncer/pgbouncer.ini
              subPath: pgbouncer.ini
            - name: pgbouncer-userlist
              mountPath: /etc/pgbouncer/userlist.txt
              subPath: userlist.txt
      volumes:
        - name: pgbouncer-config
          configMap:
            name: pgbouncer-config
        - name: pgbouncer-userlist
          configMap:
            name: pgbouncer-userlist
