apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-master-pvc
  namespace: postgresql-haproxy-pgbouncer
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-replica1-pvc
  namespace: postgresql-haproxy-pgbouncer
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-replica2-pvc
  namespace: postgresql-haproxy-pgbouncer
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi